### ISSUE TITLE
Suggestion: Include sensible (Defaults everyone can agree on)

### ISSUE THREAD

**Issue by idbrii** [aam1r/sachet#13]
tpope's [sensible](https://github.com/tpope/vim-sensible/) is an effort to create a base set of vim defaults that everyone wants. (More like `incsearch` and not `hidden`.)

It's a great initiative and it sounds like a great fit for a vim setup creator like sachet.

**Comment by thomasboyt** [comment]
While I agree that Sensible's defaults are generally "what everyone wants," I think it'd be better to integrate the various settings it toggles into Satchet's initial configuration options page, instead of just dropping in the entire plugin's configuration. Seems like Sensible would definitely be a good starting point for the next options to add to that page :)

**Comment by aam1r** [comment]
I agree with @thomasboyt. Over the next few days, I will integrate the options that sensible uses into sachet's initial configuration page.
